### ISSUE TITLE
Design subscription DeadLetter queues support

### ISSUE THREAD

**Issue by raksiv** [nitrictech/nitric#287]
It should be possible to configure dead-letter queues for topic subscriptions so that when an event cannot be delivered to the intended subscriber, it can end up in a queue for processing.

The dead letter queue is a service implementation to store messages that meet one or more of the following criteria:

Dead letter queue storing of these messages allows developers to look for common patterns and potential software problems.

- Design the interface for the DL queue in the Nitric Server (Sprint 1)

**Comment by jyecusch** [comment]
The initial design was to use a `queue` resource as the dead-letter destination. However, Azure Event Grid doesn't support dead-letter messages being sent to queues, only to storage as blobs (see: https://docs.microsoft.com/en-us/azure/event-grid/manage-event-delivery). This leaves us with a few options:

- Don't support dead-letter queues for Azure
- Process the dead-letter messages from storage and send them to a queue (i.e. we provide a service to do this)
- Provide inconsistent behaviour between clouds for dead-letters (e.g. set the name of the dead-letter target, which will be a queue in AWS, topic in PubSub, storage on Azure)
- Make dead-letter targets a unique resource. Since we _could_ subscribe a function to the write events of the dead-letter blob container in Azure. We could make it possible to do something like `deadletter.subscribe(...)` and provide similar behaviour across the clouds, even though different underlying resources would be used.

**Comment by jyecusch** [comment]
@tjholm suggests option 4 is probably the best. We could also make the dead-letter nitric resource queryable - so instead of subscribing you could run a schedule (e.g. daily) to pull the latest events off the dead-letter queue.

**Comment by raksiv** [comment]
That seems like the most flexible approach in the options.
