### ISSUE TITLE
cli: improve stack update (up) command DX enhancement

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/nitric#507]
Improvements to the `nitric stack up` command to provide succint details about the resources being deployed and the status of each deployment.

**Comment by tjholm** [comment]
Still WIP, got a version working with viewports, but there is some weird behaviour with updates and diffs causing flashing as the FPS for updates on the client end is too high and occasionally produces empty diffs on updates causing flashing on the CLI side.

Some options are:
 - Be OK with hiding overflow and just pass through content directly to the terminal (this works fine at the moment).
 - Troubleshoot render updates for the tea program on the deployment server side.
 - Don't use bubbletea (but we can still use bubbles). i.e. implement our own application lifecycle around the tea.Model instead. 

The flashing is really being caused by the difference between spinner/model updates as they occur as two separate events.

The spinners always update lines so that will render the full table, but the updates may only change one line at a time producing a small diff which renders stable but then the next spinner tick renders the full table again immediately. (this could probably be somewhat stablized by ignoring diagnostic events for now)

**Comment by tjholm** [comment]
Next steps would probably be to remove tea.NewProgram and write our own lifecycle wrapper for the output instead.
